version: "3"
services:
  proxy:
    image: nginx:latest
    ports:
      - 8080:80
    networks:
      - public-network
      - private-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - boards.api
      - boards.website

  boards.api:
    build:
      context: .
      dockerfile: Api.Dockerfile
    expose:
      - 8080
      - 8081
    networks:
      - private-network

  boards.website:
    build:
      context: .
      dockerfile: WebSite.Dockerfile
    expose:
      - 80
    networks:
      - private-network

networks:
  public-network:
    internal: false
  private-network:
    internal: true
